namespace NB.Core.Textures;

/// <summary>
/// A texture asset: the CPU header plus its GPU blob. "…top" assets carry the base level, "…mip" assets
/// carry levels 1..n-1, single-level textures carry the base only.
/// </summary>
public sealed class TextureAsset
{
    public TextureHeader Header;
    public byte[] Gpu;
    public List<LevelLayout> Levels;

    public TextureAsset(ReadOnlySpan<byte> cpu, byte[] gpu)
    {
        Header = TextureHeader.Parse(cpu);
        Gpu = gpu;
        int first = Header.HasBase ? 0 : 1;
        int last = Header.HasBase ? (Header.Levels <= 1 ? 0 : Header.Levels - 1) : Header.Levels - 1;
        // A base-carrying blob of a multi-level texture keeps its mips in the separate "mip" asset
        // unless the blob is large enough to hold them too.
        if (Header.HasBase && Header.Levels > 1)
        {
            var full = XenosTexture.Layout(Header.Width, Header.Height, Header.Levels, Header.Format, 0, Header.Levels - 1, Header.Tiled);
            last = XenosTexture.LayoutSize(full, Header.Format, Header.Tiled) * Header.Count <= gpu.Length ? Header.Levels - 1 : 0;
        }
        Levels = XenosTexture.Layout(Header.Width, Header.Height, Header.Levels, Header.Format, first, last, Header.Tiled);
    }

    /// <summary>Size of one face / frame / slice.</summary>
    public int SubresourceSize => XenosTexture.LayoutSize(Levels, Header.Format, Header.Tiled);
    public int ExpectedGpuSize => SubresourceSize * Header.Count;

    /// <summary>Decodes stored level <paramref name="index"/> of face / frame / slice <paramref name="sub"/>.
    /// Volume textures are treated as stacked 2D slices (experimental: true 3D tiling is not implemented).</summary>
    public (byte[] Rgba, int W, int H) Decode(int index = 0, int sub = 0)
    {
        var l = Levels[index];
        var data = sub == 0 ? Gpu : Gpu.AsSpan(sub * SubresourceSize).ToArray();
        return (XenosTexture.DecodeLevel(data, l, Header.Format, Header.Endian, Header.Tiled), l.Width, l.Height);
    }

    /// <summary>Builds a GPU blob for this asset's level set from a full-resolution RGBA image (mips generated by box filter).</summary>
    public static byte[] EncodeBlob(TextureHeader h, List<LevelLayout> levels, byte[] rgba, int w, int h2)
    {
        var blob = new byte[XenosTexture.LayoutSize(levels, h.Format, h.Tiled)];
        if (w != h.Width || h2 != h.Height) (rgba, w, h2) = ImageIO.Resize(rgba, w, h2, h.Width, h.Height);
        var cur = (Rgba: rgba, W: w, H: h2);
        int curLevel = 0;
        foreach (var l in levels.OrderBy(l => l.Level))
        {
            while (curLevel < l.Level) { cur = ImageIO.Half(cur.Rgba, cur.W, cur.H); curLevel++; }
            var blocks = BlockCodec.Encode(cur.Rgba, cur.W, cur.H, h.Format);
            XenosTexture.WriteLevelBlocks(blob, l, h.Format, h.Endian, h.Tiled, blocks);
        }
        return blob;
    }
}
