<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\NB.Core\NB.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenTK" Version="4.8.2" />
    <PackageReference Include="OpenTK.GLControl" Version="4.0.1" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>NBModStudio</AssemblyName>
    <Version>1.13.6</Version>
    <NoWarn>$(NoWarn);WFO1000</NoWarn>
    <ApplicationIcon>Assets\studio.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Update="Assets\*.png" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Assets\Backgrounds\*.jpg" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>